# This is where I keep my personal commands for this computer
  alias codemode="~/.pyenv/versions/2.7.6/bin/codemod.py"
  alias jsc="/System/Library/Frameworks/JavaScriptCore.framework/Resources/jsc"
  alias ll='ls -l'
  alias la='ls -A'
  alias l='ls -CF'
  alias l='ls -CF'
  alias pro="vim -O ~/.profile ~/.dotfiles/bashrc; ~/.dotfiles/profile; src"
  alias src="source ~/.profile ~/.dotfiles/bashrc; ~/.dotfiles/profile;"
  alias whoson="users  | sed 's/ /\n/g' | uniq -c | sort -n"
  alias wtf="echo 'Its okay, I, the computer, amd just messing with you, go take a break'"
  alias sls="screen -ls"
  alias sx="screen -x"
  alias ta="tmux attach"
  alias dotfiles="cd ~/.dotfiles"

  # Enable color support of ls and also add handy aliases
  if [ -x /usr/bin/dircolors ]; then
      eval "`dircolors -b`"
      alias ls='ls --color=auto'
      alias dir='dir --color=auto'
      alias vdir='vdir --color=auto'
      alias sls="screen -ls "
      alias sx="screen -x "

      alias grep='grep --color=auto'
      alias fgrep='fgrep --color=auto'
      alias egrep='egrep --color=auto'
  fi

# EXPORTS
  export PATH=$PATH:/usr/local/mysql/bin/
  export PATH=$PATH:/usr/local/git/bin/
  export PATH=/usr/local/bin/:$PATH
  export RUBYOPT=rubygems
  export PATH="/usr/local/heroku/bin:$PATH"
  export HISTCONTROL=ignoreboth

# Setting PATH for Python 3.3
# The orginal version is saved in .bash_profile.pysave
  export PATH="/Library/Frameworks/Python.framework/Versions/3.3/bin:${PATH}"

# Personal Bash Prefs

if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
fi

eval "$(pyenv init -)"
